"""Write mod/Mods/OARCommands/Scripts/unlockables.lua: the skills and cash gear that the value
commands (maxskills, unlockall) hand out, read from the class default objects in the game's pak.

Only things bought with in-game cash go in. Anything with a coin price or a Steam item ID (paid
emotes, masks, outfits, maps) is left out, and the script refuses to write a table that has one.
"""
import os

from oar_package import Package
from oar_pak import Pak

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "mod", "Mods", "OARCommands", "Scripts", "unlockables.lua")

ROOTS = ("OAR/Content/Maps/Menu/BP/Shop/", "OAR/Content/BP/Player/Skills/")
SKILL_STRUCT = "OAR/Content/BP/Player/Skills/SkillSaveStruct"
PROGRESS_STRUCT = "OAR/Content/BP/Player/Skills/SkillProgressStruct"
SKILL_BASE = "Shop_SkillBase_C"
GEAR_KINDS = {                      # base class -> kind shown in messages
    "ShopItem_Weapon_base_C": "weapon",
    "ShopItem_WeaponMod_base_C": "weapon mod",
    "ShopItem_Equipment_Base_C": "tool",
    "ShopItem_Armor_base_C": "armor",
}


def load(pak, base):
    return Package(base, pak.read(base + ".uasset"), pak.read(base + ".uexp"))


def read_classes(pak):
    """class name -> {super, path, props} for every Blueprint class under ROOTS."""
    classes = {}
    for f in sorted(pak.files):
        if not (f.endswith(".uasset") and f.startswith(ROOTS)):
            continue
        base = f[:-len(".uasset")]
        pkg = load(pak, base)
        for e in pkg.exports:
            if pkg.class_of(e) == "BlueprintGeneratedClass":
                c = classes.setdefault(e["name"], {})
                c["super"] = pkg.obj_name(e["super_index"])
                c["path"] = "/Game/" + base[len("OAR/Content/"):] + "." + e["name"]
            elif e["name"].startswith("Default__"):
                c = classes.setdefault(e["name"][len("Default__"):], {})
                c["props"] = pkg.read_properties(pkg.export_data(e))
    return classes


def chain(classes, name):
    out = []
    while name in classes and name not in out:
        out.append(name)
        name = classes[name].get("super")
    return out


def resolved(classes, name):
    """Default values with inheritance: a class default object only stores what differs from its parent."""
    props = {}
    for c in reversed(chain(classes, name)):
        props.update(classes[c].get("props", {}))
    return props


def struct_fields(pak, base, prefixes):
    """Member names of a Blueprint struct as the engine knows them (they carry a GUID suffix)."""
    pkg = load(pak, base)
    export = next(e for e in pkg.exports if pkg.class_of(e) == "UserDefinedStruct")
    _super, _children, props, _flags = pkg.read_struct(export)
    names = [p["name"] for p in props]
    return [next(n for n in names if n.startswith(prefix + "_")) for prefix in prefixes]


def is_paid(props):
    return bool(props.get("CoinCost") or props.get("SteamItemDefID"))


def main():
    pak = Pak()
    classes = read_classes(pak)
    skills, gear = [], []
    for name in sorted(classes, key=str.lower):
        c = classes[name]
        if "path" not in c:
            continue
        ch = chain(classes, name)
        props = resolved(classes, name)
        if SKILL_BASE in ch[1:]:
            tiers = len(props.get("SkillComponent", []))
            if tiers and not is_paid(props):
                skills.append((name, c["path"], tiers))
            continue
        kind = next((GEAR_KINDS[b] for b in ch[1:] if b in GEAR_KINDS), None)
        if kind and props.get("CashCost", 0) > 0 and not is_paid(props):
            gear.append((name, c["path"], kind))

    if not skills or not gear:
        raise SystemExit("found no skills or no gear; refusing to write an empty table")
    for name, _path, _ in skills + gear:
        if is_paid(resolved(classes, name)):
            raise SystemExit(f"{name} has a coin price or Steam item ID; refusing to write it")

    skill, tier = struct_fields(pak, SKILL_STRUCT, ("Skill", "Tier"))
    research_skill, progress = struct_fields(pak, PROGRESS_STRUCT, ("Skill", "Progress"))
    lines = ["-- Generated by make_unlockables.py from the game's pak. Only things bought with in-game cash:",
             "-- nothing here has a coin price or a Steam item ID.",
             "return {",
             f'  SkillFields = {{ skill = "{skill}", tier = "{tier}" }},',
             f'  ProgressFields = {{ skill = "{research_skill}", progress = "{progress}" }},',
             "  Skills = {"]
    lines += [f'    {{ name = "{n}", path = "{p}", tiers = {t} }},' for n, p, t in skills]
    lines += ["  },", "  Gear = {"]
    lines += [f'    {{ name = "{n}", path = "{p}", kind = "{k}" }},' for n, p, k in gear]
    lines += ["  },", "}"]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    kinds = {}
    for _, _, k in gear:
        kinds[k] = kinds.get(k, 0) + 1
    print(f"{len(skills)} skills, {len(gear)} gear items {kinds} -> {OUT}")


if __name__ == "__main__":
    main()
