"""Write mod/Mods/OARCommands/Scripts/maps.lua: the heists and the other map files in the game, for
the selectmap and forcemap commands.

Heists come from the lobby's map entries (ShopItem_Map_* classes): display name, the map file the
game travels to, and whether the heist is sold for coins. The other maps are every .umap in the
pak that no heist uses (lobby, tutorials, setup missions, test and demo maps).

A heist sold for coins keeps its Steam item ID here: the commands only start it when the game
itself counts it as owned. The script refuses to write a table where a paid heist's map file
could also be reached through the plain list.
"""
import os

import make_unlockables
from oar_pak import Pak

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "mod", "Mods", "OARCommands", "Scripts", "maps.lua")
PREFIX = "ShopItem_Map_"


def main():
    pak = Pak()
    classes = make_unlockables.read_classes(pak)
    files = {f.rsplit("/", 1)[-1][:-len(".umap")] for f in pak.files if f.endswith(".umap")}
    by_lower = {f.lower(): f for f in files}

    heists = []
    for name in sorted(classes, key=str.lower):
        c = classes[name]
        if not name.startswith(PREFIX) or "path" not in c:
            continue
        p = make_unlockables.resolved(classes, name)
        title, filename = p.get("Name"), p.get("Filename")
        if not title or not filename or filename.lower() not in by_lower:
            continue                                   # the base class and the dev test entry
        heists.append(dict(key=name[len(PREFIX):-len("_C")].lower(), name=title, file=by_lower[filename.lower()],
                           path=c["path"], coin=p.get("CoinCost", 0) or 0, item=p.get("SteamItemDefID", 0) or 0,
                           level=p.get("UnlockLevel", 0) or 0))
    if len(heists) < 5:
        raise SystemExit(f"only {len(heists)} heists found; refusing to write a partial table")
    for h in heists:
        if h["coin"] > 0 and not h["item"]:
            raise SystemExit(f"{h['name']} costs coins but has no Steam item ID; cannot check ownership")

    used = {h["file"] for h in heists}
    other = sorted(files - used, key=str.lower)
    paid_files = {h["file"].lower() for h in heists if h["coin"] > 0}
    if paid_files & {f.lower() for f in other}:
        raise SystemExit("a paid heist's map file is in the plain list; refusing to write")

    lines = ["-- Generated by make_maps.py from the game's pak.",
             "-- Heists: the lobby's map entries. coin > 0 means the heist is sold for coins; item is its",
             "-- Steam item ID, used to check that you own it. Other: map files no heist uses.",
             "return {", "  Heists = {"]
    for h in heists:
        lines.append(f'    {{ key = "{h["key"]}", name = "{h["name"]}", file = "{h["file"]}", coin = {h["coin"]}, '
                     f'item = {h["item"]}, level = {h["level"]},\n      path = "{h["path"]}" }},')
    lines += ["  },", "  Other = {"]
    lines += [f'    "{f}",' for f in other]
    lines += ["  },", "}"]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    paid = sum(1 for h in heists if h["coin"] > 0)
    print(f"{len(heists)} heists ({paid} sold for coins), {len(other)} other maps -> {OUT}")


if __name__ == "__main__":
    main()
