"""Write mod/Mods/OARCommands/Scripts/spawnables.lua: every spawnable Blueprint actor and its path.

The summon command uses it to turn friendly names ("goldbar") into a class ("Goldbar_C") and
the path it must load first ("/Game/BP/Items/Valuables/Goldbar.Goldbar_C").
"""
import os

import build_lists

HERE = os.path.dirname(os.path.abspath(__file__))

OUT = os.path.join(os.path.dirname(HERE), "mod", "Mods", "OARCommands", "Scripts", "spawnables.lua")


def main():
    records, from_registry = build_lists.spawnable_classes(build_lists.parse_objects())
    if not from_registry:
        raise SystemExit("asset registry not readable; refusing to write a partial table")
    lines = ["-- Generated by make_spawnables.py. Friendly name (lowercase, no _C) -> class and path.",
             "return {"]
    seen = set()
    for r in sorted(records, key=lambda r: (r["name"].lower(), r["path"])):
        if not r["path"]:
            continue
        key = r["name"].lower()
        key = key[:-2] if key.endswith("_c") else key
        if key in seen:                       # three names exist twice; keep the first path
            continue
        seen.add(key)
        lines.append(f'  ["{key}"] = {{ name = "{r["name"]}", path = "{r["path"]}" }},')
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(seen)} spawnables -> {OUT}")


if __name__ == "__main__":
    main()
